name: tensorflow210_clean
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - pillow
  - ipykernel
  - jupyterlab
  - opencv=4.5.5
  - pip
  - pip:
      - tensorflow==2.10.1
